### Register Tenant
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "email": "megumi@gmail.com",
    "password": "coba12345",
    "confirmPassword": "coba12345",
    "firstName": "Megumi",
    "lastName": "Kato",
    "phoneNumber": "085712345671",
    "userType": "TENANT"
}

### Login Tenant
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "chisato@gmail.com",
    "password": "coba12345"
}

###
GET http://localhost:4000/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJUeXBlIjoiVEVOQU5UIiwiaWF0IjoxNjg0ODI5MzIxLCJleHAiOjE2ODQ4MzExMjF9.bztyRwvn3VIGPuokF_wMNrWrzN-zNcL0alaJmXmhIqU
###
GET http://localhost:4000/tenants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJUeXBlIjoiVEVOQU5UIiwiaWF0IjoxNjg0ODIxMjc4LCJleHAiOjE2ODQ4MjMwNzh9.2nQAI83tYhzcg94wQoJYK3QYJh1z0a_JmBXKb0KvYso

###
DELETE http://localhost:4000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJUeXBlIjoiVEVOQU5UIiwiaWF0IjoxNjg0ODI5OTQ3LCJleHAiOjE2ODQ4MzE3NDd9.tpUMEl_H0-GefX9W6RS7JlhU5HtxF08LnaSECHDozVc

###
GET http://localhost:4000/coworking-spaces

### 
GET http://localhost:4000/owners/facilities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJUeXBlIjoiT1dORVIiLCJpYXQiOjE2ODU4MTkwNDksImV4cCI6MTY4NTgyMDg0OX0.5OUD1pYpz5mw_zhFU6GuvJ8KJ3fXGY4tbM2ErwBQp_0

###
GET http://api-spots-coworking.vercel.app/coworking-spaces